---
development:
  dialect: postgres
  database: main
  user: main
  password: main
  port: 4000
  host: 127.0.0.1
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://main:main@127.0.0.1:4000/assessment_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5432/assessment_production?sslmode=disable"}}
