version: '3'


services:
  # app:
    # build: .
    # ports:
    #   - "3000:3000"
    # depends_on:
    #   - main-db
    #   - test-db
    # environment:
    #   - MAIN_DB_URL=postgres://main:main@main-db:5432/main
    #   - TEST_DB_URL=postgres://test:test@test-db:5432/test
  assessment_db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=main
      - POSTGRES_PASSWORD=main
      - POSTGRES_DB=main
    volumes:
      - maindb:/var/lib/postgresql/data
    ports:
      - "4000:5432"
volumes:
  maindb:
  testdb: